services:
  - type: web
    name: ionic-app
    env: static
    buildCommand: ionic build --prod
    staticPublishPath: www
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
